apiVersion: v1
kind: Pod
metadata:
  name: pokemon-app
  labels:
    app.kubernetes.io/name: pokemon-app
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/_meta/metrics'
    prometheus.io/port: '3000'
spec:
  containers:
  - name: pokemon
    image: pokemon-service
    ports:
    - containerPort: 3000
    imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: pokemon-service
spec:
  selector:
    app.kubernetes.io/name: pokemon-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Pod
metadata:
  name: pokemon-requests
spec:
  containers:
  - name: pokemon
    image: pokemon-requests
    imagePullPolicy: Never
