apiVersion: v2
name: grafana-stack
type: application
version: 1.0.0
dependencies:
  - name: prometheus
    version: 25.27.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: grafana
    version: 8.5.2
    repository: https://grafana.github.io/helm-charts
