grafana:
  adminUser: admin
  adminPassword: admin

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://grafana-prometheus-server
          access: proxy
          isDefault: true

  grafana.ini:
    auth.anonymous:
      enabled: true
      org_role: Admin